/* eslint-disable no-console */
import fs from "node:fs";
import path from "node:path";

import { loadContentIndex } from "../src/content/content-loader";

const OUTPUT_PATH = path.resolve(
  process.cwd(),
  "src/content/generated-content.ts",
);

const generate = () => {
  const { errors, index } = loadContentIndex();

  if (errors.length > 0) {
    console.error("\n❌ Content validation failed:\n");
    for (const error of errors) {
      console.error(`  [${error.folder}] ${error.message}`);
    }
    console.error("");
    process.exit(1);
  }

  const output = `// Auto-generated by scripts/generate-content-index.ts
// Do not edit manually.

import type { ContentIndex } from './content-schema'

export const contentIndex = ${JSON.stringify(index, null, 2)} satisfies ContentIndex
`;

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");

  console.log(
    `✅ Content index generated: ${path.relative(process.cwd(), OUTPUT_PATH)}`,
  );
  console.log(
    `   ${index.pages.length} page(s), ${index.pages.reduce((sum, p) => sum + p.sections.length, 0)} section(s)`,
  );
};

generate();
