/* eslint-disable no-console */
import fs from "node:fs";
import path from "node:path";

import { loadContentIndex } from "../src/content/content-loader";

const OUTPUT_PATH = path.resolve(
  process.cwd(),
  "src/content/generated-content.ts",
);

const toImportName = (pageIndex: number, sectionIndex: number) =>
  `Section_${pageIndex}_${sectionIndex}`;

const generate = () => {
  const { errors, index } = loadContentIndex();

  if (errors.length > 0) {
    console.error("\n❌ Content validation failed:\n");
    for (const error of errors) {
      console.error(`  [${error.folder}] ${error.message}`);
    }
    console.error("");
    process.exit(1);
  }

  const imports: string[] = [];
  const pageEntries: string[] = [];

  for (const [pageIndex, page] of index.pages.entries()) {
    const sectionEntries: string[] = [];

    for (const [sectionIndex, section] of page.sections.entries()) {
      const importName = toImportName(pageIndex, sectionIndex);
      const relativePath = path.relative(
        path.dirname(OUTPUT_PATH),
        path.resolve(process.cwd(), section.filePath),
      );
      imports.push(`import ${importName} from "${relativePath}";`);
      sectionEntries.push(
        `      { Component: ${importName}, order: ${section.order} }`,
      );
    }

    pageEntries.push(`    {
      folderPath: ${JSON.stringify(page.folderPath)},
      meta: ${JSON.stringify(page.meta)},
      sections: [
${sectionEntries.join(",\n")}
      ],
    }`);
  }

  const output = `// Auto-generated by scripts/generate-content-index.ts
// Do not edit manually.

import type { RuntimeContentIndex } from "./content-schema";

${imports.join("\n")}

export const contentIndex = {
  pages: [
${pageEntries.join(",\n")}
  ],
} satisfies RuntimeContentIndex;
`;

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");

  console.log(
    `✅ Content index generated: ${path.relative(process.cwd(), OUTPUT_PATH)}`,
  );
  console.log(
    `   ${index.pages.length} page(s), ${index.pages.reduce((sum, p) => sum + p.sections.length, 0)} section(s)`,
  );
};

generate();
